export const AUTH = "AUTH";
export const USER = "USER";
export const LOGOUT = "LOGOUT";

export const FORMSAVE = "FORMSAVE";
export const CALLBOOK_SUCESSFULL = "CALLBOOK_SUCESSFULL";
export const CALLBOOK_REQUEST = "CALLBOOK_REQUEST";
export const CALLBOOK_FAILURE = "CALLBOOK_FAILURE";

export const FORM_SAVE_REQUEST = "FORM_SAVE_REQUEST";
export const FORM_SAVE_SUCCESS = "FORM_SAVE_SUCCESS";
export const FORM_SAVE_FAILURE = "FORM_SAVE_FAILURE";

export const GETMENTOR = "GETMENTOR";
export const UPDATEMENTOR = "UPDATEMENTOR";

export const USER_LIST_MENTOR = "USER_LIST_MENTOR";

export const MENTORS_LIST_SUCCESS = "MENTORS_LIST_SUCCESS";
export const MENTORS_LIST_REQUEST = "MENTORS_LIST_REQUEST";
export const MENTORS_LIST_FAILURE = "MENTORS_LIST_FAILURE";

export const MENTOR_DELETE_SUCCESS = "MENTOR_DELETE_SUCCESS";
export const MENTOR_DELETE_REQUEST = "MENTOR_DELETE_REQUEST";
export const MENTOR_DELETE_FAILURE = "MENTOR_DELETE_FAILURE";

export const MENTOR_UPDATE_SUCCESS = "MENTOR_UPDATE_SUCCESS";
export const MENTOR_UPDATE_REQUEST = "MENTOR_UPDATE_REQUEST";
export const MENTOR_UPDATE_FAILURE = "MENTOR_UPDATE_FAILURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const GET_MENTOR_REQUEST = "GET_MENTOR_REQUEST";
export const GET_MENTOR_SUCCESS = "GET_MENTOR_SUCCESS";
export const GET_MENTOR_FAILURE = "GET_MENTOR_FAILURE" ;

