const LoginString = {
  login_google: "LOGIN WITH GOOGLE",
  login: "LOGIN",
  mentee_button: "MENTEE",
  mentor_button: "MENTOR",
  email_label: "Email",
  email_placeholder: "email@example.com",
  password_label: "Password",
  password_placeholder: "Your Password here",
  forgot_text: " Forgot Your Username/Password?",
  click_here: "Click Here",
  // section part start here
  name: "Kapil Batra",
  jobrole: "Product Designer at MetaCube Software",
  study: "Studied B-tech from IIT",
  location: "Jaipur",
  language: "English,Hindi",
  session: "Available Sessions",
  mentorship: "Mentorship Program",
  timezone: " Your Timezone(Asia/calcutta)",
  update: "Updated",
  thu_day: "THU",
  fry_day: "FRY",
  sat_day: "SAT",
  sun_day: "SUN",
  mon_day: "MON",
  date1: "12 JUN",
  date2: "13 JUN",
  date3: "14 JUN",
  date4: "15 JUN",
  date5: "16 JUN",
  slot: "12 slots",
  view: "View All",
  timeslot: "Available Time Slot",
  book_session: "Book Session For 6 Jun,2:30 PM",

  //footer part start here
  icon: "Edukith",
  icon_info:
    "Amet minim mallit non deserunt uliamce est sit aliqua dolar do amet sint.Velit offcia consequat",
  menu: "Menu",
  sub_menu: "Become a Mentor",
  sub_menu1: "Our mentors",
  sub_menu2: "About us",
  sub_menu3: "Privacy policy",
  link: "Links",
  link1: "FAQs",
  link2: "Connect us",
  link3: "Career",
  link4: "Code of conduct",
  contact: "Contact Info",
  contact1: "2118 thornridge cir,syracuse,Connecti 35642",
  contact2: "(316) 555-0116",
  contact3: "hello@edukith.com",
  social: "Social media",
};
export default LoginString;
