const LoginString = {
  login_google: "LOGIN WITH GOOGLE",
  login: "LOGIN",
  mentee_button: "MENTEE",
  mentor_button: "MENTOR",
  email_label: "Email",
  email_placeholder: "email@example.com",
  password_label: "Password",
  password_placeholder: "Your Password here",
  forgot_text: " Forgot Your Username/Password?",
  click_here: "Click Here",
  // section part start here
  name: "Kapil Batra",
  jobrole: "Product Designer at MetaCube Software",
  study: "Studied B-tech from IIT",
  location: "Jaipur",
  language: "English,Hindi",
  session: "Available Sessions",
  mentorship: "Mentorship Program",
  timezone: " Your Timezone(Asia/calcutta)",
  update: "Updated",
  thu_day: "THU",
  fry_day: "FRY",
  sat_day: "SAT",
  sun_day: "SUN",
  mon_day: "MON",
  date1: "12 JUN",
  date2: "13 JUN",
  date3: "14 JUN",
  date4: "15 JUN",
  date5: "16 JUN",
  slot: "12 slots",
  view: "View All",
  timeslot: "Available Time Slot",
  book_session: "Book Session For 6 Jun,2:30 PM",
};
export default LoginString;
